### ISSUE TITLE
element, setLinkedMusic

### ISSUE THREAD

**Issue by Edensel** [Edensel/harmony-hub#39]
Hello Martin,

I hope you are good.

I have two issue for you to resolve.

1.  **element**

Kindly check your code and define **element** since it is not. I am getting errors from this end on the function Card.

2. **setlikedMusic** 

You have used setLikedMusic instead of **setlikedMusic** on line 17 and 24.

Kindly resolve, ping me when done.

Thanks,

**Comment by Edensel** [comment]
Martin ping me when down

**Comment by TintinSDev** [comment]
@Edensel this is resolved, kindly check
